# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
            -   id: check-yaml
            -   id: check-added-large-files
                args: [ '--maxkb=1024' ]
            -   id: end-of-file-fixer
    -   repo: https://github.com/mxr/unkey
        rev: v0.0.1
        hooks:
            -   id: unkey
    -   repo: https://github.com/MarcoGorelli/auto-walrus
        rev: v0.2.2
        hooks:
            -   id: auto-walrus
    -   repo: https://github.com/jazzband/pip-tools
        rev: 7.3.0
        hooks:
            -   id: pip-compile
    -   repo: https://github.com/psf/black
        rev: 23.9.1
        hooks:
            -   id: black
    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.0.292
        hooks:
            -   id: ruff
                args: [--fix ]
    -   repo: https://github.com/jorisroovers/gitlint
        rev: v0.19.1
        hooks:
            -   id: gitlint
default_language_version:
    python: python3.12
